# 1 Import Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder


# 2 Get Data

In [2]:
Data = pd.read_csv("C:/Users/prasad/Downloads/pronostico_dataset.csv", sep=";")
Data

ID        age  systolic_bp  diastolic_bp  cholesterol       prognosis
0        0  77.196340    85.288742     80.021878    79.957109     retinopathy
1        1  63.529850    99.379736     84.852361   110.382411     retinopathy
2        2  69.003986   111.349455    109.850616   100.828246     retinopathy
3        3  82.638210    95.056128     79.666851    87.066303     retinopathy
4        4  78.346286   109.154591     90.713220    92.511770     retinopathy
...    ...        ...          ...           ...          ...             ...
5995  5995  49.611850    94.857639     86.615671   107.643986  no_retinopathy
5996  5996  63.099686   100.039527     93.515186   104.971404     retinopathy
5997  5997  55.562243    98.421446    102.697875   120.875951     retinopathy
5998  5998  63.468956   106.809289     88.060631   106.052213     retinopathy
5999  5999  62.506825    96.900784     86.878033   108.625436  no_retinopathy

[6000 rows x 6 columns]

In [3]:
Data.shape

(6000, 6)

In [4]:
Data.drop(columns='ID',inplace=True)

In [5]:
# we use labelencoder on target variable 
label_encoder= LabelEncoder()
Data.iloc[:,-1]=label_encoder.fit_transform(Data.iloc[:,-1])

In [6]:
#Age outlier replace by median value of the age feature

median=Data.loc[Data['age']<82,'age'].median()
median2=Data.loc[Data['age']>37,'age'].median()
Data.loc[Data.age>82,'age']=np.nan
Data.loc[Data.age<37,'age']=np.nan
Data.fillna(median,inplace=True)
Data.fillna(median2,inplace=True)

In [7]:
#systolic_bp outlier replace by median value of the age feature

median=Data.loc[Data['systolic_bp']<128,'systolic_bp'].median()
median2=Data.loc[Data['systolic_bp']>73,'systolic_bp'].median()
Data.loc[Data.systolic_bp>128,'systolic_bp']=np.nan
Data.loc[Data.systolic_bp<73,'systolic_bp']=np.nan
Data.fillna(median,inplace=True)
Data.fillna(median2,inplace=True)

In [8]:
#diastolic_bp outlier replace by median value of the age feature

median=Data.loc[Data['diastolic_bp']<115,'diastolic_bp'].median()
median2=Data.loc[Data['diastolic_bp']>65,'diastolic_bp'].median()
Data.loc[Data.diastolic_bp>115,'diastolic_bp']=np.nan
Data.loc[Data.diastolic_bp<65,'diastolic_bp']=np.nan
Data.fillna(median,inplace=True)
Data.fillna(median2,inplace=True)

In [9]:
#cholesterol outlier replace by median value of the age feature

median=Data.loc[Data['cholesterol']<127,'cholesterol'].median()
median2=Data.loc[Data['cholesterol']>73,'cholesterol'].median()
Data.loc[Data.cholesterol>127,'cholesterol']=np.nan
Data.loc[Data.cholesterol<73,'cholesterol']=np.nan
Data.fillna(median,inplace=True)
Data.fillna(median2,inplace=True)

In [10]:
# Splitting the independent and dependent variables
X = Data.drop(columns="prognosis",axis=1)
Y = Data.prognosis
X.shape,Y.shape

((6000, 4), (6000,))

## FEATURE SCALING

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
# standardization 
std_scaler = StandardScaler()
X_scaler = std_scaler.fit_transform(X) 
print(X_scaler)

[[ 2.12861278 -1.49920548 -1.11897174 -2.06484113]
 [ 0.42438837 -0.10356533 -0.58939197  1.02215518]
 [ 1.10701842  1.08197356  2.15123868  0.05277541]
 ...
 [-0.56917997 -0.19847897  1.36706315  2.08684533]
 [ 0.41679484  0.63229355 -0.23766006  0.58280688]
 [ 0.29681608 -0.34909274 -0.36731164  0.8438899 ]]


In [13]:
#Spliting the variable into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.20, random_state=2903)


# MODEL BUILDING

## GradientBoostingClassifier

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
gbc_model = GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                                       learning_rate=0.1, loss='deviance', max_depth=3,
                                       max_features=None, max_leaf_nodes=None,
                                       min_impurity_decrease=0.0,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0, n_estimators=100,
                                       n_iter_no_change=None,
                                       random_state=2903, subsample=1.0, tol=0.0001,
                                       validation_fraction=0.1, verbose=0,
                                       warm_start=False)
gbc_model.fit(X_train,y_train)

GradientBoostingClassifier(loss='deviance', random_state=2903)

### Validation of model

In [15]:
y_pred_gbc_train= gbc_model.predict(X_train)

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [17]:
print("Accuracy of training model",accuracy_score(y_train,y_pred_gbc_train))
print("==============================================================================")
print("Confusion Matrics",confusion_matrix(y_train,y_pred_gbc_train))
print("==============================================================================")
print("Classificaton Report ",classification_report(y_train,y_pred_gbc_train))

Accuracy of training model 0.7722916666666667
Confusion Matrics [[1712  611]
 [ 482 1995]]
Classificaton Report                precision    recall  f1-score   support

           0       0.78      0.74      0.76      2323
           1       0.77      0.81      0.78      2477

    accuracy                           0.77      4800
   macro avg       0.77      0.77      0.77      4800
weighted avg       0.77      0.77      0.77      4800



In [18]:
y_pred_gbc_test= gbc_model.predict(X_test)

In [19]:
print("Accuracy of testing model",accuracy_score(y_test,y_pred_gbc_test))
print("==============================================================================")
print("Confusion Matrics",confusion_matrix(y_test,y_pred_gbc_test))
print("==============================================================================")
print("Classificaton Report",classification_report(y_test,y_pred_gbc_test))

Accuracy of testing model 0.7483333333333333
Confusion Matrics [[431 159]
 [143 467]]
Classificaton Report               precision    recall  f1-score   support

           0       0.75      0.73      0.74       590
           1       0.75      0.77      0.76       610

    accuracy                           0.75      1200
   macro avg       0.75      0.75      0.75      1200
weighted avg       0.75      0.75      0.75      1200



In [20]:
#Create pickel file using serialization
# import pickle
# pickle_out=open("gbc_model.pkl","wb") 
# pickle.dump(gbc_model,pickle_out)
# pickle_out.close()

In [21]:
import pickle

In [22]:
with open('gbc_model_pickle','wb') as f:
    pickle.dump(gbc_model,f)
    f.close()